### ISSUE TITLE
PubPeer Column Blank

### ISSUE THREAD

**Issue by dunldj** [PubPeerFoundation/pubpeer_zotero_plugin#16]
Hello, 

I'm using Zotero v. 5.0.93 for Windows. I've recently installed the PubPeer plugin 0.0.6. It is enabled and a column appears in my library.

However, for every article, the column is blank. I've ensured that I have files with PubPeer comments in my library (e.g. this one: https://pubpeer.com/publications/4399282A80691D9421B497E8316CF6 among several others). Still nothing shows up. 

 I've tried restarted Zotero (and resinstalling the plugin), to no avail. I've also tried selecting the option to "Check for Comments on PubPeer" (which doesn't seem to do anything that I can see).

And ideas about what else the issue might be? Interaction with another plug-in? User error? Bad luck?

Thanks for any advice,
Dan

**Comment by dunldj** [comment]
> However, for every article, the column is blank. I've ensured that I have files with PubPeer comments in my library (e.g. this one: https://pubpeer.com/publications/4399282A80691D9421B497E8316CF6 among several others). Still nothing shows up.> 

Quick update: Perhaps it is a matter of slow retrieval time (or imperfect retrieval)? I did see a few articles populate with comments, though not all the articles I had confirmed had PP comments.

**Comment by retorquere** [comment]
links should update whenever an item changes, at start, and every 24 hours (if you leave zotero running that long).

**Comment by retorquere** [comment]
We're on Zotero 7 now.
