### ISSUE TITLE
latest release has no xpi file

### ISSUE THREAD

**Issue by champagnealexandre** [PubPeerFoundation/pubpeer_zotero_plugin#27]
I’m not really familiar with building this type of target, and the latest release doesn’t have the resulting xpi file. Is it possible to add it to the release?

Thanks!

**Comment by retorquere** [comment]
I forgot to check in the release action, the release is running now.

**Comment by champagnealexandre** [comment]
wonderful thank you @retorquere !

**Comment by champagnealexandre** [comment]
incidentally, i do confirm everything seems to be working fine with the plugin on the current beta version of zotero
