### ISSUE TITLE
Add PubPeer item tab

### ISSUE THREAD

**Issue by retorquere** [PubPeerFoundation/pubpeer_zotero_plugin#3]
16 **PubPeer** comments from Leonid Schneider, Campanula Garganica, Roland Baron...
https://pubpeer.com/publications/1B0EAC54A32060F75B01DD128A0BA6

Most recent comment on October 9, 2019

**Comment by retorquere** [comment]
Waiting for Travis to be set up so I can start generating test releases.

This implementation monkey-patches `ZoteroItemPane.viewItem` because it always fires when any tab there is selected, and it's hard-coded to expect exactly 3 columns.

**Comment by brandonStell** [comment]
:robot: this is your friendly neighborhood build bot announcing [test build 0.0.1.1](https://github.com/PubPeerFoundation/pubpeer_zotero_plugin/releases/download/builds/zotero-pubpeer-0.0.1.1.xpi) ("ncu")

Install in Zotero by downloading [test build 0.0.1.1](https://github.com/PubPeerFoundation/pubpeer_zotero_plugin/releases/download/builds/zotero-pubpeer-0.0.1.1.xpi), opening the Zotero "Tools" menu, selecting "Add-ons", open the gear menu in the top right, and select "Install Add-on From File...".

**Comment by brandonStell** [comment]
:robot: this is your friendly neighborhood build bot announcing [test build 0.0.1.4](https://github.com/PubPeerFoundation/pubpeer_zotero_plugin/releases/download/builds/zotero-pubpeer-0.0.1.4.xpi) ("rebuild")

Install in Zotero by downloading [test build 0.0.1.4](https://github.com/PubPeerFoundation/pubpeer_zotero_plugin/releases/download/builds/zotero-pubpeer-0.0.1.4.xpi), opening the Zotero "Tools" menu, selecting "Add-ons", open the gear menu in the top right, and select "Install Add-on From File...".

**Comment by brandonStell** [comment]
This looks good to me.
