### ISSUE TITLE
installation to zotero 6 prevents normal operation of zotero

### ISSUE THREAD

**Issue by Guy-LF** [PubPeerFoundation/pubpeer_zotero_plugin#31]
installed to zotero following the Zotero version 6 release.  Installed on a windows 10 machine.

once enabled, the pubpeer column shows momentarily in the standard view pane, with no effect on the presentation of data in the other columns.

after a few seconds the data disappears from the view pane.   Column headers remain visible, but no data can be displayed.   Disabling the pubpeer plugin corrects this issue.

**Comment by browaeys** [comment]
Same behaviour on a MacOS 12.3 machine.

**Comment by retorquere** [comment]
I have it reproducible. No idea what causes it yet. BBT uses the exact same mechanism.

**Comment by Guy-LF** [comment]
I removed the pubpeer add-on, and installed the test build 0.0.13.25.
The problem persisted.
I repeated the remove pubpeer installed the test build a second time and now it seems to work.

I'll let someone else close the issue. Thank you for looking into this

**Comment by retorquere** [comment]
new version is scheduled
