### ISSUE TITLE
PubPeer plugin is incompatible with Zotero 6.0.14

### ISSUE THREAD

**Issue by borisbarbour** [PubPeerFoundation/pubpeer_zotero_plugin#40]
After an automatic update to Zotero 6.0.14, the PubPeer plugin was disabled and the add-ons manager reports that the plugin is incompatible with the new version.

**Comment by retorquere** [comment]
I can't find anything that would cause this, and when I install the pubpeer plugin on 6.0.15, it is enabled.

**Comment by borisbarbour** [comment]
Apologies. I've now realised that there is a problem updating Zotero itself. It's likely that is the source of the problem. I'll report back once I've sorted that out.
