### ISSUE TITLE
Interferes with "New Feed" dialog

### ISSUE THREAD

**Issue by gustavdelius** [PubPeerFoundation/pubpeer_zotero_plugin#48]
When this plugin is enabled in Zotero 6.0.30 then the "New Feed" dialog (see https://www.zotero.org/support/feeds#subscribing_to_feeds) no longer works. No matter what feed URL one puts into the dialog, the "Save" button stays disabled.

**Comment by dstillman** [comment]
@retorquere Was the fix from https://github.com/PubPeerFoundation/pubpeer_zotero_plugin/issues/38 never rolled out?

**Comment by gustavdelius** [comment]
Sorry, I had not noticed that I was still using version 0.0.14. The problem is fixed in version 0.0.16
