### ISSUE TITLE
Zot7 issue: breaks rendering and provides empty tree to zot ui

### ISSUE THREAD

**Issue by andreala** [PubPeerFoundation/pubpeer_zotero_plugin#51]
4T5D8H8E-fio-ldJex8NBIL3k
7B28T4FH-fio-yNCleqND7Cuk

When enabling 0.0.16.49.72, rendering of references in Zotero disappears due to 
[JavaScript Error: "TypeError: this.tree is null" {file: "chrome://zotero/content/itemTree.js" line: 2906}]
_renderHasAttachmentCell/<@chrome://zotero/content/itemTree.js:2906:13

(one per cit in chosen collection)

**Comment by retorquere** [comment]
that is not the relevant error.

a new drop will build here in a few minutes, please test that

**Comment by andreala** [comment]
It is the symptom, (there are file.io ids attached).

Will test new build and report back.
