### ISSUE TITLE
Zotero Library becomes a blank screen with PubPeer 1.0.2

### ISSUE THREAD

**Issue by Temperche** [PubPeerFoundation/pubpeer_zotero_plugin#57]
### Debug log ID

8ZZFP6V4-fio-6muOPrLA25qa

### What happened?

I installed the new PubPeer 1.0.2 plugin, and after restarting Zotero, I get shown "Loading items..." and then get shown a white blank screen instead of the usual message "Loading library...". Disabling the plugin and restarting Zotero fixes the issue. I have attached the log ID.

**Comment by retorquere** [comment]
A new build will drop here shortly to test, but you will have to upgrade Zotero; you're on 7.0.8, 7.0.10 is the latest.

**Comment by Temperche** [comment]
Resolved, but now I face the same issue as described here: https://github.com/PubPeerFoundation/pubpeer_zotero_plugin/issues/49#issuecomment-2487246067
